spring:
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200

kafka:
  bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  topic:
    out: client-events-topic