kafkastore.bootstrap.servers=SSL://kafka1:29092,SSL://kafka2:29093,SSL://kafka3:29094
kafkastore.security.protocol=SSL

kafkastore.ssl.truststore.location=/etc/schema-registry/secrets/schema-registry.truststore.jks
kafkastore.ssl.truststore.password=password-schema-registry

kafkastore.ssl.keystore.location=/etc/schema-registry/secrets/schema-registry.keystore.jks
kafkastore.ssl.keystore.password=password-schema-registry
kafkastore.ssl.key.password=password-schema-registry

listeners=http://0.0.0.0:8081
host.name=schema-registry