security.protocol=SSL

ssl.keystore.location=/etc/kafka/admin/admin.keystore.jks
ssl.keystore.password=password-admin
ssl.key.password=password-admin

ssl.truststore.location=/etc/kafka/secrets/kafka1.truststore.jks
ssl.truststore.password=password-kafka1

ssl.endpoint.identification.algorithm=