spring:
  kafka:
    bootstrap-servers: kafka4:29095,kafka5:29096,kafka6:29097
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 3
      properties:
        schema.registry.url: http://schema-registry:8081


kafka:
  topics:
    in: filter-product-topic
    out: recommendation-product-topic

hdfs:
  url: hdfs://hadoop-namenode:9000
  path: /data/analytics

analytics:
  column: category
  values:
    - Электроника